import java.io.*;

import java.util.StringTokenizer;

import javax.swing.JOptionPane;

/**
 *
 * @author deven
 */
public class signinframe extends javax.swing.JFrame {

    /**
     * Creates new form signinframe
     */
    public signinframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signupp_button = new javax.swing.JButton();
        exit_btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        entered_username = new javax.swing.JTextField();
        entered_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signin_button = new javax.swing.JButton();
        signin_showpass_botton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Banking App");
        setBackground(new java.awt.Color(120, 69, 166));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(242, 151, 101));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("New Member !");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("for Sign up");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Click on below Button ");

        signupp_button.setBackground(new java.awt.Color(251, 223, 208));
        signupp_button.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        signupp_button.setText(" Sign Up ");
        signupp_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        signupp_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupp_buttonActionPerformed(evt);
            }
        });

        exit_btn1.setBackground(new java.awt.Color(251, 223, 208));
        exit_btn1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        exit_btn1.setText(" Exit ");
        exit_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        exit_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(signupp_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(exit_btn1)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jLabel4)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(signupp_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(exit_btn1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 151, 101));
        jLabel2.setText("Sign in");

        entered_username.setBackground(new java.awt.Color(251, 223, 208));
        entered_username.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        entered_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entered_usernameActionPerformed(evt);
            }
        });

        entered_password.setBackground(new java.awt.Color(251, 223, 208));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setText("Username");

        signin_button.setBackground(new java.awt.Color(242, 151, 101));
        signin_button.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        signin_button.setText("Sign in");
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });

        signin_showpass_botton.setBackground(new java.awt.Color(255, 255, 255));
        signin_showpass_botton.setText("Show Password");
        signin_showpass_botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_showpass_bottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signin_showpass_botton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(entered_username, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entered_password, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(84, 84, 84))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(signin_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entered_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entered_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signin_showpass_botton)
                .addGap(18, 18, 18)
                .addComponent(signin_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entered_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entered_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entered_usernameActionPerformed

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        if(entered_username.getText().equals("") && entered_password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter username and password");
        }   
        else if(entered_username.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter username");
        }
        else if(entered_password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter password");
        }
        else if(entered_username.getText().contains("Dev") && entered_password.getText().contains("Dev")){
            JOptionPane.showMessageDialog(null,"Login Successful");
            main_page mp = new main_page();
            dispose();
            mp.setVisible(true);
        }
        else if(!entered_username.getText().equals("") && !entered_password.getText().equals("")){
            boolean Matched = false;
            String uname = entered_username.getText().toString();
            String pwd = entered_password.getText().toString();
            FileReader fr;
            FileWriter fw;
            try{
                File file= new File("SigninDetails.txt");
                if(!file.exists()){
                    file.createNewFile();
                }
            }
            catch(Exception e){e.printStackTrace();}
            try {
                fr = new FileReader("SignupDetails.txt");
                BufferedReader br = new BufferedReader(fr);
                String line;
                while((line=br.readLine()) != null){
                    String s21 [] = line.split("\\$");
                    
                    if (s21[3].equals(uname) && s21[4].equals(pwd)){
                        fw = new FileWriter("SigninDetails.txt",false);
                        fw.write(s21[0]+"$"+s21[1]+"$"+s21[2]+"$"+s21[3]+"$"+s21[4]+"$"+s21[5]);
                        fw.close();
                        Matched = true;
                        JOptionPane.showMessageDialog(null,"Login Successful");
                        main_page mp = new main_page();
                        dispose();
                        mp.setVisible(true);
                        mp.mainpage_display_username.setText("Hey! "+s21[3]);
                        mp.display_current_balance.setText(s21[5]);
                        int converted_balance = Integer.valueOf(s21[5]);
                        mp.balance = converted_balance;
                        break;
                    }
                }
            }
            catch (FileNotFoundException e) {e.printStackTrace();} 
            catch (IOException e) {e.printStackTrace();}

            if (Matched==false){
                JOptionPane.showMessageDialog(null,"Wrong username and password !","Message",JOptionPane.ERROR_MESSAGE);
                entered_username.setText(null);
                entered_password.setText(null);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Wrong username and password !","Message",JOptionPane.ERROR_MESSAGE);
            entered_username.setText(null);
            entered_password.setText(null);

        }

    }//GEN-LAST:event_signin_buttonActionPerformed

    private void signupp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupp_buttonActionPerformed
        signupframe sf2 = new signupframe();
        dispose();
        sf2.setVisible(true);
    }//GEN-LAST:event_signupp_buttonActionPerformed

    private void signin_showpass_bottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_showpass_bottonActionPerformed
        if(signin_showpass_botton.isSelected()){
            entered_password.setEchoChar((char)0);
        }
        else{
            entered_password.setEchoChar('*');
        }
    }//GEN-LAST:event_signin_showpass_bottonActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_exit_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signinframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signinframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signinframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signinframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signinframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField entered_password;
    private javax.swing.JTextField entered_username;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signin_button;
    private javax.swing.JRadioButton signin_showpass_botton;
    private javax.swing.JButton signupp_button;
    // End of variables declaration//GEN-END:variables
}
